# https://www.netlify.com/docs/netlify-toml-reference/
[build]
  base = "./"
  publish = "./"
  command = "npm run build"
  functions = "api"
[dev]
  base = "./"
  publish = "./"
  command = "npm run serve"
  targetPort = 4000
[functions]
  included_files = []
